FROM python:3.12-slim

WORKDIR /app

# 1. Instalar as bibliotecas de sistema atualizadas (Debian 12)
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    libxcb1 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

# 2. Instalar as tuas bibliotecas Python
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "web/web_app.py"]