
services:
  api_backend:
    image: goncalofcouto/api_backend:latest
    environment:
      - DATABASE_URL_MASTER=postgresql://admin:123@db_master:5432/antifurto_db
      - DATABASE_URL_REPLICA=postgresql://admin:123@db_replica:5432/antifurto_db
    build: 
      context: ./Backend  
    ports:
      - "8000:8000"            
    networks:
      - rede_cluster              
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure    

  dashboard_frontend:
    image: goncalofcouto/dashboard:latest    
    build: 
      context: ./dashboard-antifurto 
    ports:
      - "8080:80"                
    networks:
      - rede_cluster
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  db_master:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=master      # Master
      - POSTGRESQL_REPLICATION_USER=repl_user   # Cria um utilizador só para fazer as cópias
      - POSTGRESQL_REPLICATION_PASSWORD=senha_replica
      - POSTGRESQL_USERNAME=admin               
      - POSTGRESQL_PASSWORD=123
      - POSTGRESQL_DATABASE=antifurto_db
    ports:
      - "5432:5432"
    networks:
      - rede_cluster
    volumes:
      - dados_master:/bitnami/postgresql
    deploy:
      restart_policy:
        condition: on-failure

  db_replica:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave       # Slave
      - POSTGRESQL_MASTER_HOST=db_master        # Indica o Master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user   # Usa o mesmo utilizador de cópia
      - POSTGRESQL_REPLICATION_PASSWORD=senha_replica
      - POSTGRESQL_PASSWORD=123
    networks:
      - rede_cluster
    volumes:
      - dados_replica:/bitnami/postgresql
    deploy:
      restart_policy:
        condition: on-failure

  docker-proxy:
      image: tecnativa/docker-socket-proxy
      environment:
        - SERVICES=1
        - TASKS=1
        - NODES=1
        - POST=1
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock 
      networks:
        - rede_cluster
      deploy:
        placement:
          constraints:
            - node.role == manager 

networks:
  rede_cluster:
    driver: overlay   
    attachable: true 

volumes:
  dados_master:
  dados_replica:

# docker stack deploy -c docker-compose.yml teste_local | docker service ls
